name: Update Blocklist

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ⭐ 加这一行

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          chmod +x merge.sh
          ./merge.sh

      - name: Commit result
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "update blocklist" || echo "no changes"
          git push
